-- ============================================================
-- Customer Seed Data
-- Run AFTER 001_schema.sql
-- ============================================================

INSERT INTO public.customers (name_en, name_ar, area, location_url, price_per_bottle, delivery_days, active, sort_order) VALUES
-- Saturday customers (6 total; first 3 Saturday-only, next 3 Saturday+Tuesday)
('Mafraq camp',             'كامب المفرق',           'Mafraq',         'https://maps.app.goo.gl/p8UouKkrSM4VjJrR7?g_st=ic', NULL, ARRAY['Saturday'],             TRUE, 1),
('Golden Moon Transport',   'جولدن مون',             'Mafraq',         '',                                                   NULL, ARRAY['Saturday'],             TRUE, 2),
('Bannu Gul',               'بنو المفرق',            'Mafraq',         'https://maps.app.goo.gl/QPGASJnD1PBP5mbv5?g_st=ic', NULL, ARRAY['Saturday'],             TRUE, 3),
('bannu 17',                'بنو 17',                'musaffah',       '',                                                   NULL, ARRAY['Saturday','Tuesday'],   TRUE, 4),
('bannu 26',                'بنو 26',                'musaffah',       '',                                                   NULL, ARRAY['Saturday','Tuesday'],   TRUE, 5),
('bannu 37',                'بنو 37',                'musaffah',       '',                                                   NULL, ARRAY['Saturday','Tuesday'],   TRUE, 6),

-- Monday customers (22)
('Royal Bannu',             'مطعم ابوظبي',           'khalidiya',      '',                                                   NULL, ARRAY['Monday'],               TRUE, 7),
('Raju Shahi',              'راجو شاهي',             'Muroor',         'https://maps.apple/p/R.z4B9E-tBbZaH',               NULL, ARRAY['Monday'],               TRUE, 8),
('Gaurav Pandey',           'غاوراف باندي',          'Hamdan Street',  'https://maps.apple/p/QsXBnonWraJ2Po',               NULL, ARRAY['Monday'],               TRUE, 9),
('Alsannan Marketing',      'السنان ماركتينج',       'Electra Street', 'https://maps.apple/p/ZILsVnaPzREN9c',               NULL, ARRAY['Monday'],               TRUE, 10),
('Jade properties',         'مكتب ساجد',             'Electra Street', '',                                                   NULL, ARRAY['Monday'],               TRUE, 11),
('mazroui building',        'برج المزروعي',          'najda street',   '',                                                   NULL, ARRAY['Monday'],               TRUE, 12),
('abubaker',                'ابوبكر',                'Najda',          '',                                                   NULL, ARRAY['Monday'],               TRUE, 13),
('jahid',                   'جاهد',                  'Tanker',         'https://maps.app.goo.gl/XAN5fYx1kdxoL1e46?g_st=ac', NULL, ARRAY['Monday'],               TRUE, 14),
('syrian murror',           'سوري المرور',           '',               'https://maps.app.goo.gl/KxpisYHeWGpDWU9b8?g_st=ac', NULL, ARRAY['Monday'],               TRUE, 15),
('Ahmed alanani',           'احمد العناني',          '',               'https://maps.app.goo.gl/Nee1jkTbM8L9Bxjn6?g_st=ac', NULL, ARRAY['Monday'],               TRUE, 16),
('Tariq',                   'طارق',                  '',               '',                                                   NULL, ARRAY['Monday'],               TRUE, 17),
('Safaa',                   'صفاء',                  '',               '',                                                   NULL, ARRAY['Monday'],               TRUE, 18),
('Yasmeen',                 'ياسمين',                '',               '',                                                   NULL, ARRAY['Monday'],               TRUE, 19),
('abdelrahman shabiya',     'عبد الرحمن الشعبيه',   '',               '',                                                   NULL, ARRAY['Monday'],               TRUE, 20),
('mhamed Abdullah',         'محمد عبدالله',          '',               '',                                                   NULL, ARRAY['Monday'],               TRUE, 21),
('abdelrahman ibrahim',     'عبد الرحمن ابراهيم',   '',               '',                                                   NULL, ARRAY['Monday'],               TRUE, 22),
('Mohamed alzebair',        'محمد الزبير',           '',               '',                                                   NULL, ARRAY['Monday'],               TRUE, 23),
('arafa almuntazah',        'عرفت المنتزه',          '',               '',                                                   NULL, ARRAY['Monday'],               TRUE, 24),
('marhaba smoke',           'مرحبا للتدخين',         '',               '',                                                   NULL, ARRAY['Monday'],               TRUE, 25),
('faihaa',                  'فيحاء',                 '',               '',                                                   NULL, ARRAY['Monday'],               TRUE, 26),
('faihaa neighbor',         'جنب فيحاء',             '',               '',                                                   NULL, ARRAY['Monday'],               TRUE, 27),
('abdelhalim',              'عبدالحليم',             '',               '',                                                   NULL, ARRAY['Monday'],               TRUE, 28),

-- Tuesday customers (21 Tuesday-only; plus bannu 17/26/37 above = 24 total)
('Bannu Office',            'مكتب بنو',              '',               '',                                                   NULL, ARRAY['Tuesday'],              TRUE, 29),
('Tamm Factory',            'مصنع تم',               '',               '',                                                   NULL, ARRAY['Tuesday'],              TRUE, 30),
('Hussam',                  'حسام 26',               '',               '',                                                   NULL, ARRAY['Tuesday'],              TRUE, 31),
('Ahmed 26',                'احمد 26',               '',               '',                                                   NULL, ARRAY['Tuesday'],              TRUE, 32),
('Mohamed Hassan',          'محمد حسن',              '',               '',                                                   NULL, ARRAY['Tuesday'],              TRUE, 33),
('Mohamed Ismail',          'محمد اسماعيل',          '',               '',                                                   NULL, ARRAY['Tuesday'],              TRUE, 34),
('Hadi',                    'هادي',                  '',               '',                                                   NULL, ARRAY['Tuesday'],              TRUE, 35),
('Abdulraziq',              'عبدالرزاق',             '',               '',                                                   NULL, ARRAY['Tuesday'],              TRUE, 36),
('Mohamed Suhaji',          'محمد السوهاجي',         '',               '',                                                   NULL, ARRAY['Tuesday'],              TRUE, 37),
('Samih',                   'سامح',                  '',               '',                                                   NULL, ARRAY['Tuesday'],              TRUE, 38),
('Shaheen',                 'شاهين',                 '',               '',                                                   NULL, ARRAY['Tuesday'],              TRUE, 39),
('Mohamed Joel',            'محمد جويل',             '',               '',                                                   NULL, ARRAY['Tuesday'],              TRUE, 40),
('Mohamed Ali',             'محمد علي',              '',               '',                                                   NULL, ARRAY['Tuesday'],              TRUE, 41),
('Bilal',                   'بلال',                  '',               '',                                                   NULL, ARRAY['Tuesday'],              TRUE, 42),
('Ayub',                    'ايوب',                  '',               '',                                                   NULL, ARRAY['Tuesday'],              TRUE, 43),
('Adham',                   'أدهم',                  '',               '',                                                   NULL, ARRAY['Tuesday'],              TRUE, 44),
('Ahmed Rajab',             'احمد رجب',              '',               '',                                                   NULL, ARRAY['Tuesday'],              TRUE, 45),
('Mahmoud Kafrawi',         'محمود الكفراوي',        '',               '',                                                   NULL, ARRAY['Tuesday'],              TRUE, 46),
('Ali Albot',               'علي البوت',             '',               '',                                                   NULL, ARRAY['Tuesday'],              TRUE, 47),
('Abu Saeed',               'ابوسعيد',               '',               '',                                                   NULL, ARRAY['Tuesday'],              TRUE, 48),
('Ahmed Najjar',            'احمد النجار',           '',               '',                                                   NULL, ARRAY['Tuesday'],              TRUE, 49),

-- Wednesday customers (22)
('Bannu Mafraq',            'بنو المفرق',            '',               '',                                                   NULL, ARRAY['Wednesday'],            TRUE, 50),
('Mahmoud',                 'محمود االشوامخ',        'Shawamikh',      '',                                                   NULL, ARRAY['Wednesday'],            TRUE, 51),
('Ibarahim',                'ابراهيم',               'Shawamikh',      '',                                                   NULL, ARRAY['Wednesday'],            TRUE, 52),
('Amir alsudani',           'أمير السوداني',         'Shawamikh',      '',                                                   NULL, ARRAY['Wednesday'],            TRUE, 53),
('Ahmed algabari',          'احمد الجعبري',          'Shawamikh',      '',                                                   NULL, ARRAY['Wednesday'],            TRUE, 54),
('Mohmd hassan sudani',     'محمد حسن',              'Shawamikh',      '',                                                   NULL, ARRAY['Wednesday'],            TRUE, 55),
('Abu bshoy',               'ابو بشوي',              'Shakhboot',      '',                                                   NULL, ARRAY['Wednesday'],            TRUE, 56),
('Ayman',                   'ايمن شخبوط',            'Shakhboot',      '',                                                   NULL, ARRAY['Wednesday'],            TRUE, 57),
('Kenafa',                  'كنافه',                 'Shakhboot',      '',                                                   NULL, ARRAY['Wednesday'],            TRUE, 58),
('Kandi',                   'ماندي',                 'Shakhboot',      '',                                                   NULL, ARRAY['Wednesday'],            TRUE, 59),
('Mahmoud alkaddi',         'محمود الفاضي',          'Shakhboot',      '',                                                   NULL, ARRAY['Wednesday'],            TRUE, 60),
('Ahmed magdi',             'احمد مجدي',             'Shakhboot',      '',                                                   NULL, ARRAY['Wednesday'],            TRUE, 61),
('Karefour staff',          'سكن كارفور',            'Shakhboot',      '',                                                   NULL, ARRAY['Wednesday'],            TRUE, 62),
('Mohmd nadi',              'محمد نادي',             'Shakhboot',      '',                                                   NULL, ARRAY['Wednesday'],            TRUE, 63),
('Ikram',                   'اكرام',                 'Baniyas',        '',                                                   NULL, ARRAY['Wednesday'],            TRUE, 64),
('Mai gt one',              'ماي جي تي ون',          'Baniyas',        '',                                                   NULL, ARRAY['Wednesday'],            TRUE, 65),
('Sudani baniyas',          'سوداني بني ياس',        'Baniyas',        '',                                                   NULL, ARRAY['Wednesday'],            TRUE, 66),
('Ahmed kamil',             'احمد كامل',             'Baniyas',        '',                                                   NULL, ARRAY['Wednesday'],            TRUE, 67),
('Mustafa abu alnaja',      'مصطفى ابو النجا',       'Baniyas',        '',                                                   NULL, ARRAY['Wednesday'],            TRUE, 68),
('Mohmd jamal',             'محمد جمال',             'Baniyas',        '',                                                   NULL, ARRAY['Wednesday'],            TRUE, 69),
('Yasmeen Alsham',          'ياسمين الشام',          '',               '',                                                   NULL, ARRAY['Wednesday'],            TRUE, 70),
('Filipino banni yas',      'فلبيني بني ياس',        '',               '',                                                   NULL, ARRAY['Wednesday'],            TRUE, 71),

-- Thursday customers (23)
('Rq talks',                'ار كيو توكسس',          'Shabiya 12',     'https://maps.app.goo.gl/GSAH8zqQk7QA6LZa6?g_st=ic', NULL, ARRAY['Thursday'],             TRUE, 72),
('White Mart',              'وايت مارت',             'Shabiya 12',     'https://maps.apple/p/S.dbMy_jSMo~8n',               NULL, ARRAY['Thursday'],             TRUE, 73),
('Azam',                    '',                      'MBZ',            'https://maps.app.goo.gl/SVP8J9W7jsysCa7u8?g_st=ic', NULL, ARRAY['Thursday'],             TRUE, 74),
('Havana Ladies tailoring', '',                      'Shabiya 12',     'https://maps.apple/p/5eXGb6Dk0gR6BA',               NULL, ARRAY['Thursday'],             TRUE, 75),
('Print by advertising',    '',                      'Shabiya 12',     'https://maps.apple/p/5eXGb6Dk0gR6BA',               NULL, ARRAY['Thursday'],             TRUE, 76),
('Confident Electronics and Computer', '',           'Shabiya 12',     'https://maps.apple/p/5eXGb6Dk0gR6BA',               NULL, ARRAY['Thursday'],             TRUE, 77),
('Indian Ladies Saloon',    '',                      'Shabiya 12',     'https://maps.apple/p/5eXGb6Dk0gR6BA',               NULL, ARRAY['Thursday'],             TRUE, 78),
('mohamed fadel',           'محمد فاضل',             '',               '',                                                   NULL, ARRAY['Thursday'],             TRUE, 79),
('abdelaal',                'عبدالعال',              '',               '',                                                   NULL, ARRAY['Thursday'],             TRUE, 80),
('Indian MBZ',              'هندي محمد بن زايد',     '',               '',                                                   NULL, ARRAY['Thursday'],             TRUE, 81),
('Shubair',                 'شوبير',                 '',               '',                                                   NULL, ARRAY['Thursday'],             TRUE, 82),
('Um Ahmed',                'ام احمد',               '',               '',                                                   NULL, ARRAY['Thursday'],             TRUE, 83),
('Elsisi',                  'السيسي',                '',               '',                                                   NULL, ARRAY['Thursday'],             TRUE, 84),
('Mahmud Somali',           'محمود الصومالي',        '',               '',                                                   NULL, ARRAY['Thursday'],             TRUE, 85),
('Saloon menhali',          'صالون منهالي',          '',               '',                                                   NULL, ARRAY['Thursday'],             TRUE, 86),
('Um Deeri',                'ام ديري',               '',               '',                                                   NULL, ARRAY['Thursday'],             TRUE, 87),
('Pakistani n15',           'باكستاني n 15',         '',               '',                                                   NULL, ARRAY['Thursday'],             TRUE, 88),
('Hunnah Clothe Store',     'هنا محل ملابس',         '',               '',                                                   NULL, ARRAY['Thursday'],             TRUE, 89),
('OK Travel',               'اوكي للسفر',            '',               '',                                                   NULL, ARRAY['Thursday'],             TRUE, 90),
('Khubaib Buiilding',       'بناية خباب',            '',               '',                                                   NULL, ARRAY['Thursday'],             TRUE, 91),
('Imran Ahmed',             'عمران احمد',            '',               '',                                                   NULL, ARRAY['Thursday'],             TRUE, 92),
('Landmark Phones',         'لاندمارك',              '',               '',                                                   NULL, ARRAY['Thursday'],             TRUE, 93),
('Prestige Saloon',         'صالون برستيج',          '',               '',                                                   NULL, ARRAY['Thursday'],             TRUE, 94);
